### ISSUE TITLE
All Access Launch checklist

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/EDD-Site#1202]
### Must fix before live
- [x] Something about this All Access conditional breaks download functionality: https://github.com/easydigitaldownloads/edd-all-access/blob/be5f1adaa993f1677564a49e0b61486ee6288be9/includes/functions/downloading-functions.php#L142 With `$price_id_to_deliver != 0 && !$file_key` removed, downloading works as expected for all products (it seems). On staging, [Aweber](http://staging.easydigitaldownloads.com/downloads/aweber/) does not work while [Add To Cart Popup](http://staging.easydigitaldownloads.com/downloads/add-cart-popup/) does. Notice the Price ID and Download File indexes one their edit screens (0 vs 1).
- [x] [All Access Downloads page](http://staging.easydigitaldownloads.com/your-account/all-access-downloads/) uses FacetWP (and should, there are too many extensions). The "Download Now" link is an EDD purchase form styled to just look like a link and of course taken over by All Access. When you use the FacetWP filter to narrow down output, the purchase forms drop their All Access influence and output the entire purchase form until you refresh the page. This wasn't happening on an older version of FacetWP I had locally. After an update, this happens.

### To go live
- [x] Push code update for custom functions plugin (merge issue/24)
- [x] Push code update for theme
- [x] Publish `All Access Downloads` page
- [x] Import FacetWP `Facet: Download Categories` and `Template: All Access Downloads` (get latest from staging)
- [x] Publish `All Access Pass` download
- [x] Add All Access Pass to menu

### Planned enhancements (may happen either before or after launch)
- [x] Additional All Access Pass promotions in various places, like the account page.
- [ ] Show download button on downloads archive for pass holders
- [ ] Place All Access output above standard purchase form. I gave this a good try but every approach caused problems. Tricky stuff. I'll have to revisit.

### Google Analytics
- [x] We have a trigger on the Pricing Page for when someone clicks the Core Extensions Bundle call-to-action button. That's changing to All Access Pass. `eddwp_send_ga_action( 'event', 'pricing_page', 'all_access_pass', 'All Access Pass' )`

-----

If you see something missing on staging that must happen, but you don't see it mentioned above, please do not assume it's not happening. This is not a complete task list by any means.

**Comment by pippinsplugins** [comment]
Updated todo list to have a code push for theme and custom functions plugin.

**Comment by SDavisMedia** [comment]
@mintplugins @pippinsplugins Just updated my notes. See "Must fix before live" section. For both, you'll need to have purchased a [pass](http://staging.easydigitaldownloads.com/downloads/all-access-pass/) to see the issues.

**Comment by pippinsplugins** [comment]
@mintplugins could you please help Sean fix the first item first thing tomorrow? It's the highest priority item on your todo list.

@SDavisMedia I would love to see FacetWP work but please disable it for initial launch. We'll fix that later.

**Comment by SDavisMedia** [comment]
Cool cool.

**Comment by SDavisMedia** [comment]
Live. 🎉

**Comment by pippinsplugins** [comment]
Woot!

**Comment by SDavisMedia** [comment]
Closing. New issues opened for the two remaining tasks.
